Mediamart/Models/Article_Cate.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mediamart.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Article_Cate
    {
        public long Id { get; set; }
        public string Cate { get; set; }
        public string Name { get; set; }
        public Nullable<System.DateTime> Createdate { get; set; }
        public string Createby { get; set; }
        public string Link { get; set; }
        public string Image { get; set; }
    }
}

Mediamart/Areas/Admin/Controllers/Article_CateController.cs
using PagedList;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Globalization;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Mediamart.Models;
using Mediamart.Utils;

namespace Mediamart.Areas.Admin.Controllers
{
    [Permission(Module = "articlecate")]
    public class Article_CateController : BaseController
    {
        public ActionResult Index(int? page, string textsearch, string chanel, string status, string start_date, string end_date, string im_start_date, string im_end_date)
        {
            var model = from a in db.Article_Cate
                        select a;
            if (!string.IsNullOrEmpty(textsearch))
            {
                model = model.Where(a => a.Name.StartsWith(textsearch));
                ViewBag.textsearch = textsearch;
            }

            if (!string.IsNullOrEmpty(start_date))
            {
                DateTime s = DateTime.ParseExact(start_date, "dd/MM/yyyy", CultureInfo.InvariantCulture);
                model = model.Where(a => a.Createdate >= s);
                ViewBag.start_date = start_date;
            }
            if (!string.IsNullOrEmpty(end_date))
            {
                DateTime s = DateTime.ParseExact(end_date, "dd/MM/yyyy", CultureInfo.InvariantCulture);
                s = s.AddDays(1);
                model = model.Where(a => a.Createdate <= s);
                ViewBag.end_date = end_date;
            }
            IEnumerable<Article_Cate> data = model as IEnumerable<Article_Cate>;
            int pageSize = 10;
            int pageNumber = (page ?? 1);
            return View(data.OrderByDescending(a => a.Createdate).ToPagedList(pageNumber, pageSize));
        }

        [Permission(Module = "articlecate.add")]
        [HttpPost]
        public ActionResult Create()
        {
            return PartialView("~/Areas/Admin/Views/Article_cate/_Create.cshtml", null);
        }

        [HttpPost, ValidateInput(false)]
        [ValidateAntiForgeryToken]
        public ActionResult CreateConfirm([Bind(Include = "")] Article_Cate article_cate)
        {
            try
            {
                article_cate.Createby = User.Identity.Name;
                article_cate.Createdate = DateTime.Now;
                db.Article_Cate.Add(article_cate);
                db.SaveChanges();
                SetAlert("Đã lưu thông tin thành công.", "success");
                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {

            }
            SetAlert("Lưu thông tin không thành công. Hãy kiểm tra lại.", "danger");
            return RedirectToAction("Index");

        }
        [Permission(Module = "articlecate.edit")]
        [HttpPost]
        public ActionResult Edit(long Id)
        {
            var model = db.Article_Cate.Find(Id);
            return PartialView("~/Areas/Admin/Views/Article_cate/_Edit.cshtml", model);
        }

        [HttpPost, ValidateInput(false)]
        [ValidateAntiForgeryToken]
        public ActionResult EditCate([Bind(Include = "")] Article_Cate article_cate)
        {
            try
            {
                db.Entry(article_cate).State = EntityState.Modified;
                db.SaveChanges();
                SetAlert("Đã lưu thông tin thành công.", "success");
                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {

            }
            SetAlert("Lưu thông tin không thành công. Hãy kiểm tra lại.", "danger");
            return RedirectToAction("Index");

        }
        [Permission(Module = "articlecate.delete")]
        public ActionResult Delete(long Id)
        {
            try
            {
                var model = db.Article_Cate.Find(Id);
                db.Article_Cate.Remove(model);
                db.SaveChanges();
                SetAlert("Đã xóa thành công.", "success");
            }
            catch (Exception ex)
            {
                SetAlert(ex.Message, "danger");
            }

            return RedirectToAction("Index");
        }
    }
}

Mediamart/Areas/Admin/Views/Article_Cate/Index.cshtml
@model PagedList.IPagedList<Mediamart.Models.Article_Cate>
@using PagedList.Mvc;
@{
    ViewBag.Title = "Article Cate";
    var index = 0;
}


<!-- validation by Bootstrap -->
<div class="card">
    <div class="card-header">Form filter</div>
    <div class="card-body">
        <div class="row">
            <div class="col-md-12">
                <form class="needs-validation" novalidate>
                    <div class="form-row">
                        <div class="col-md-2 mb-2">
                            <label for="ticket-name" class="col-form-label">Tìm kiếm</label>
                            <div class="">
                                <input type="text" class="form-control" name="textsearch" value="@ViewBag.textsearch">
                            </div>
                        </div>
                        <div class="col-md-3 mb-3">
                            <label for="ticket-type" class="col-sm-9 col-form-label">Ngày tạo</label>
                            <div class="input-daterange input-group" data-provide="datepicker" data-date-format="dd/mm/yyyy">
                                <input class="form-control" name="start_date" value="@ViewBag.start_date">
                                <div class="input-group-prepend">
                                    <span class="input-group-text">to</span>
                                </div>
                                <input class="form-control" name="end_date" value="@ViewBag.end_date">
                            </div>
                        </div>
                    </div>
                    <button class="btn btn-primary" type="submit"><i class="ti ti-filter"></i> Tìm kiếm</button>
                    @if (User.IsInModule("articlecate.add"))
                    {
                        <a class="btn btn-info" href="#" id="add"><i class="ti ti-plus"></i> Tạo mới</a>
                    }
                </form>
            </div>

        </div>
    </div>
</div>


<div class="card">
    <div class="card-header">
        <h3 class="card-title">Table database</h3>
    </div>
    <div class="card-body">
        <table class="table table-sm" id="table">
            <thead>
                <tr>
                    <th>#</th>
                    <th>Mã phân loại</th>
                    <th>Tên chi tiết</th>
                    <th>Link</th>
                    <th>Image</th>
                    <th>Ngày tạo</th>
                    <th>#</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    index++;
                    <tr>
                        <td style="display:none">@item.Id</td>
                        <td>@index</td>
                        <td>@item.Cate</td>
                        <td>@item.Name</td>
                        <td>@item.Link</td>
                        <td>
                            <img src="@item.Image" width="100" />
                        </td>
                        <td>
                            @if (item.Createdate != null)
                            {@item.Createdate.Value.ToString("dd/MM/yyyy")}
                        </td>
                        <td>
                            <div class="btn-group">
                                @if (User.IsInModule("articlecate.edit"))
                                {
                                    <a class="btn btn-outline-light edit" href="#"><i class="ti ti-pencil-alt"></i></a>
                                }
                                @if (User.IsInModule("articlecate.delete"))
                                {
                                    <a class="btn btn-outline-light" href="/admin/article_cate/delete/@item.Id" onclick="return confirm('Bạn muốn xóa dòng này?')" title="xóa sản phẩm"><i class="ti ti-trash text-danger"></i></a>
                                }
                            </div>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
        <div class="row">
            <div class="col-sm-6">
                <div class="showing">Showing @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of @Model.PageCount</div>
            </div>
            <div class="col-sm-6">
                @Html.PagedListPager(Model, page => Url.Action("Index", new { page, textsearch = ViewBag.textsearch, chanel = ViewBag.chanel, status = ViewBag.status, start_date = ViewBag.start_date, end_date = ViewBag.end_date }))
            </div>
        </div>
    </div>
</div>

@section scripts{
    <script>
        $("#add").click(function () {
            $.ajax({
                type: "POST",
                url: "/Admin/Article_cate/Create",
                success: function (response) {
                    $('#createbody').html(response);
                    $('#createmodal').modal('show');
                }
            });
        });
        $("#table .edit").click(function () {
            var Id = $(this).closest("tr").find("td").eq(0).html();
            $.ajax({
                type: "POST",
                url: "/Admin/Article_cate/Edit",
                data: '{Id: "' + Id + '" }',
                contentType: "application/json; charset=utf-8",
                dataType: "html",
                success: function (response) {
                    $('#createbody').html(response);
                    $('#createmodal').modal('show');
                }
            });
        });

    </script>

}

Mediamart/Areas/Admin/Views/Article_Cate/_Create.cshtml
@model Mediamart.Models.Article_Cate
@{

}
<div class="card">
    <div class="card-header">
        <h3 class="card-title">Phân loại bài viết</h3>
    </div>
    <div class="card-body">
        @using (Html.BeginForm("CreateConfirm", "Article_Cate", new { area = "Admin" }))
        {
            @Html.AntiForgeryToken()
        <div class="form-horizontal">

            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                @Html.EditorFor(model => model.Cate, new { htmlAttributes = new { @class = "form-control", @placeholder = "Mã" } })
            </div>
            <div class="form-group">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control", @placeholder = "Tên chi tiết" } })
            </div>
            <div class="form-group">
                @Html.EditorFor(model => model.Link, new { htmlAttributes = new { @class = "form-control", @placeholder = "Link" } })
            </div>
            <div class="form-group">
                @Html.EditorFor(model => model.Image, new { htmlAttributes = new { @class = "form-control", id = "txtImage" } })
                <a href="#" id="btnSelectImage">Chọn ảnh</a>
            </div>

            <div class="form-group text-center">
                <button type="submit" class="btn btn-primary"><i class="ti ti-check"></i> Lưu</button>
                <button type="button" class="btn btn-danger" data-dismiss="modal"><i class="ti ti-close"></i> Thoát</button>
            </div>

        </div>
        }
    </div>
</div>


<script>
    $(document).ready(function () {
        $('#btnSelectImage').on('click', function (e) {
            e.preventDefault();
            var finder = new CKFinder();
            finder.selectActionFunction = function (url) {
                $('#txtImage').val(url);
            };
            finder.popup();
        })
    })
</script>

Mediamart/Areas/Admin/Views/Article_Cate/_Edit.cshtml
@model Mediamart.Models.Article_Cate
@{

}
<div class="card">
    <div class="card-header">
        <h3 class="card-title">Phân loại bài viết</h3>
    </div>
    <div class="card-body">
        @using (Html.BeginForm("EditCate", "Article_Cate", new { area = "Admin" }))
        {
            @Html.AntiForgeryToken()
            <div class="form-horizontal">

                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                @Html.HiddenFor(model => model.Id)
                @Html.HiddenFor(model => model.Createby)
                @Html.HiddenFor(model => model.Createdate)
                <div class="form-group">
                    @Html.EditorFor(model => model.Cate, new { htmlAttributes = new { @class = "form-control", @placeholder = "Mã" } })
                </div>
                <div class="form-group">
                    @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control", @placeholder = "Tên chi tiết" } })
                </div>
                <div class="form-group">
                    @Html.EditorFor(model => model.Link, new { htmlAttributes = new { @class = "form-control", @placeholder = "Link" } })
                </div>
                <div class="form-group">
                    @Html.EditorFor(model => model.Image, new { htmlAttributes = new { @class = "form-control", id = "txtImage" } })
                    <a href="#" id="btnSelectImage">Chọn ảnh</a>
                </div>

                <div class="form-group text-center">
                    <button type="submit" class="btn btn-primary"><i class="ti ti-check"></i> Lưu</button>
                    <button type="button" class="btn btn-danger" data-dismiss="modal"><i class="ti ti-close"></i> Thoát</button>
                </div>

            </div>
        }
    </div>
</div>



<script>
    $(document).ready(function () {
        $('#btnSelectImage').on('click', function (e) {
            e.preventDefault();
            var finder = new CKFinder();
            finder.selectActionFunction = function (url) {
                $('#txtImage').val(url);
            };
            finder.popup();
        })
    })
</script>