Mediamart/Models/A_Station.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mediamart.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class A_Station
    {
        public string Id { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public string Model { get; set; }
        public int Price { get; set; }
        public int CountImport { get; set; }
        public int CountExport { get; set; }
        public string StationId { get; set; }
    }
}

Mediamart/Areas/Admin/Controllers/A_StationController.cs
using Mediamart.Areas.Admin.Data.Accessary;
using Mediamart.Models;
using Mediamart.Utils;
using NLog;
using PagedList;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Globalization;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using static Mediamart.Utils.Common;

namespace Mediamart.Areas.Admin.Controllers
{
    [Permission(Module = "station")]
    public class A_StationController : BaseController
    {
        Logger logger = LogManager.GetCurrentClassLogger();
        public ActionResult Index(int? page, string textsearch, string chanel, string status, string start_date, string end_date)
        {
            var model = from a in db.A_Station
                        select a;

            if (!string.IsNullOrEmpty(textsearch))
            {
                model = model.Where(a => a.Name.Contains(textsearch)
                || a.Model.Contains(textsearch)
                || a.Code.Contains(textsearch));
                ViewBag.textsearch = textsearch;
            }
            if (!string.IsNullOrEmpty(status))
            {
                if (status.Equals("0"))
                {
                    model = model.Where(a => a.CountImport - a.CountExport > 0);
                    ViewBag.status = status;
                }
                else
                {
                    model = model.Where(a => a.CountImport - a.CountExport == 0);
                    ViewBag.status = status;
                }
            }
            if (!string.IsNullOrEmpty(chanel))
            {
                model = model.Where(a => a.StationId == chanel);
                ViewBag.chanel = chanel;
            }
            ViewBag.station = db.AspNetUsers.Where(a => a.AspNetRoles.FirstOrDefault(r => r.Id == Roles.KEY) != null).ToList();
            if (User.IsInModule("station.user"))
            {
                model = model.Where(a => a.StationId == User.Identity.Name);
            }
            int pageSize = 10;
            int pageNumber = (page ?? 1);
            return View(model.OrderBy(a => a.Name).ToPagedList(pageNumber, pageSize));
        }
        [Permission(Module = "station.add")]
        public ActionResult Create()
        {
            var user = db.AspNetUsers.FirstOrDefault(a => a.UserName == User.Identity.Name);
            var model = new A_Export_Model()
            {
                Items = new List<Models.A_Export_Items>(),
                Hub = user.Hub,
                CusName = user.FullName,
                Address = user.Address,


            };
            return View(model);
        }
        [HttpPost]
        public ActionResult Create([Bind(Include = "")] A_Export_Model model, string WarrantiCode)
        {
            string msg = "Có lỗi xảy ra trong quá trình lưu phiếu.";
            try
            {
                string station;
                //tài khoản trạm thì lấy luôn, tài khoản thợ thì chuyển về trạm
                var cr_user = db.AspNetUsers.FirstOrDefault(a => a.UserName == User.Identity.Name);
                if (User.IsInRole(Roles.KTV))
                {
                    //station = cr_user.Createby;
                    var s = db.AspNetUsers.FirstOrDefault(a => a.Zone == cr_user.Zone && a.AspNetRoles.FirstOrDefault(r => r.Id == Roles.KEY) != null);
                    station = s.UserName;
                }
                else
                {
                    station = cr_user.UserName;
                }
                //đề xuất trong phiếu bảo hành sẽ phải tạo phiếu hoàn xác
                long rId = 0;
                if (model.WarrantiId > 0)
                {
                    //tạo phiếu hoàn xác
                    var revoke = new A_Revoke();

                    revoke.Createdate = DateTime.Now;
                    revoke.Createby = User.Identity.Name;
                    revoke.WarrantiId = model.WarrantiId;
                    revoke.WarrantiCode = WarrantiCode;
                    revoke.Hub = model.Hub;
                    revoke.StationId = station;
                    db.A_Revoke.Add(revoke);
                    db.SaveChanges();
                    rId = revoke.Id;
                }

                //tạo phiếu đề xuất
                var export = new A_Export();

                export.CusName = model.CusName;
                export.Hub = model.Hub;
                export.Center = model.Center;
                export.Import_Warehouse = station;
                export.Address = model.Address;
                export.Export_Warehouse = model.Export_Warehouse;
                export.Note = model.Note;
                export.Createdate = DateTime.Now;
                export.Createby = User.Identity.Name;
                export.WarrantiId = model.WarrantiId;
                db.A_Export.Add(export);
                db.SaveChanges();

                int quantity = 0;
                int total = 0;
                int amount = 0;
                if (model.Items.Count() > 0)
                {
                    foreach (var item in model.Items)
                    {
                        var check_station = db.A_Station.FirstOrDefault(a => a.StationId == station && a.Code == item.ProductCode);
                        int isHas = check_station.CountImport - check_station.CountExport;
                        int tot = item.Price * item.Quantity;
                        var _item = new A_Export_Items()
                        {
                            ProductCode = item.ProductCode,
                            ProductName = item.ProductName,
                            ProductModel = item.ProductModel,
                            Quantity = item.Quantity,
                            Price = item.Price,
                            Amount = tot,
                            Total = tot,
                            WarrantiCode = item.WarrantiCode,
                            Note = item.Note,
                            ExportId = export.Id,
                            Status = (isHas > 0) ? 1 : 0,

                        };
                        db.A_Export_Items.Add(_item);
                        //
                        //đề xuất trong phiếu bảo hành sẽ phải tạo phiếu hoàn xác
                        if (model.WarrantiId > 0)
                        {
                            var _rItem = new A_Revoke_Items()
                            {
                                ProductCode = item.ProductCode,
                                ProductName = item.ProductName,
                                ProductModel = item.ProductModel,
                                Quantity = item.Quantity,
                                Price = item.Price,
                                Amount = tot,
                                Total = tot,
                                WarrantiCode = item.WarrantiCode,
                                Note = item.Note,
                                RevokeId = rId
                            };
                            db.A_Revoke_Items.Add(_rItem);
                        }
                        quantity = quantity + item.Quantity;
                        total = total + tot;
                        amount = amount + tot;

                    }
                    //add linh kiện vào phiếu xuất luôn
                    db.SaveChanges();
                }
                export.Quantity = quantity;
                export.Total = total;
                export.Amount = amount;
                // nếu kỹ thuật viên tạo phiếu thì phải đợi trạm xác nhận mới chuyển lên trên
                // tạo trạng thái cho trạm xác nhận
                // nếu linh kiện còn ở trạm thì tạo phiếu nội bộ trạm xác nhận KTV luôn
                var check_phieu = db.A_Export_Items.Where(a => a.ExportId == export.Id && a.Status == 0);
                if (check_phieu.Count() > 0)
                {
                    //phiếu đề xuất lên trên
                    export.Status = Common.Create_Accessary.KTV_CREATE_ORDER;
                }
                else
                {
                    //phiếu đề xuất nội bộ
                    export.Status = Common.Create_Accessary.KTV_CREATE_USE;
                }
                if (station != User.Identity.Name && check_phieu != null)
                {
                    //tao thong bao
                    Signal.SendSignal signal = new Signal.SendSignal();
                    Notification notif = new Notification()
                    {
                        SentTo = station,
                        Createdate = DateTime.Now,
                        Title = String.Format(TitleNotif.accessary_ktv_use, WarrantiCode),
                        DetailsURL = String.Format(TitleNotif.url_accessary, export.Id)
                    };
                    signal.Save(notif);
                }
                db.Entry(export).State = EntityState.Modified;

                var log = new A_Export_Log()
                {
                    Createdate = DateTime.Now,
                    Createby = User.Identity.Name,
                    ExportId = export.Id,
                    Description = " Tạo phiếu đề xuất linh kiện"
                };
                db.A_Export_Log.Add(log);

                db.SaveChanges();

                SetAlert("Phiếu đề xuất được tạo thành công.", "success");
                return RedirectToAction("Index", "A_Export");
            }
            catch (Exception ex)
            {
                SetAlert(msg, "danger");
                return View(model);
            }
        }
        [HttpPost]
        public ActionResult KTVCreate([Bind(Include = "")] A_Export_Model model, string WarrantiCode)
        {
            string msg = "Có lỗi xảy ra trong quá trình lưu phiếu.";
            try
            {
                string station;
                //tài khoản trạm thì lấy luôn, tài khoản thợ thì chuyển về trạm

Mediamart/Areas/Admin/Views/A_Station/Create.cshtml
@model Mediamart.Areas.Admin.Data.Accessary.A_Export_Model
@{
    ViewBag.Title = "Station";
    //int index = 0;
}

<div class="card">
    <div class="card-header">
        <h3 class="card-title">Đề xuất linh kiện</h3>
    </div>
    <div class="card-body">
        @using (Html.BeginForm("Create", "A_Station", FormMethod.Post, new { area = "Admin", enctype = "multipart/form-data" }))
        {
            @Html.AntiForgeryToken()
            <div class="form-horizontal">

                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                @Html.HiddenFor(model => model.Id)
                <div class="form-group row">
                    <div class="col-md-6">
                        <div class="form-group row">
                            @Html.Label("Trung tâm", htmlAttributes: new { @class = "control-label col-md-4" })
                            <div class="col-md-8">@Html.EditorFor(model => model.Center, new { htmlAttributes = new { @class = "form-control" } })</div>
                        </div>
                        <div class="form-group row">
                            @Html.Label("hub", htmlAttributes: new { @class = "control-label col-md-4" })
                            <div class="col-md-8">@Html.EditorFor(model => model.Hub, new { htmlAttributes = new { @class = "form-control" } })</div>
                        </div>
                        <div class="form-group row">
                            @Html.Label("Tên người nhận", htmlAttributes: new { @class = "control-label col-md-4" })
                            <div class="col-md-8">@Html.EditorFor(model => model.CusName, new { htmlAttributes = new { @class = "form-control" } })</div>
                        </div>
                        <div class="form-group row">
                            @Html.Label("Kho nhận", htmlAttributes: new { @class = "control-label col-md-4" })
                            <div class="col-md-8">@Html.EditorFor(model => model.Import_Warehouse, new { htmlAttributes = new { @class = "form-control" } })</div>
                        </div>
                        <div class="form-group row">
                            @Html.Label("Địa chỉ", htmlAttributes: new { @class = "control-label col-md-4" })
                            <div class="col-md-8">@Html.EditorFor(model => model.Address, new { htmlAttributes = new { @class = "form-control" } })</div>
                        </div>
                        <div class="form-group row">
                            @Html.Label("Xuất tại kho", htmlAttributes: new { @class = "control-label col-md-4" })
                            <div class="col-md-8">@Html.EditorFor(model => model.Export_Warehouse, new { htmlAttributes = new { @class = "form-control" } })</div>
                        </div>
                        <div class="form-group row">
                            @Html.Label("Lý do xuất", htmlAttributes: new { @class = "control-label col-md-4" })
                            <div class="col-md-8">@Html.EditorFor(model => model.Note, new { htmlAttributes = new { @class = "form-control" } })</div>
                        </div>

                    </div>
                    <div class="col-md-12 access">
                        <table class="col-md-12 table table-bordered" style="color:#fff">
                            <thead class="bg-danger">
                                <tr>
                                    <th>Model</th>
                                    <th>Mã LK</th>
                                    <th>Tên LK</th>

                                    <th class="hidden">Số lượng</th>
                                    <th>Đơn giá</th>
                                </tr>
                            </thead>
                            <tbody id="tblBills">
                                @for (var i = 0; i < Model.Items.Count(); i++)
                                {
                                    //index++;
                                    <tr>
                                        <td>@Html.EditorFor(model => model.Items[i].ProductModel, new { htmlAttributes = new { @class = "form-control" } })</td>
                                        <td>@Html.EditorFor(model => model.Items[i].ProductCode, new { htmlAttributes = new { @class = "form-control" } })</td>
                                        <td>@Html.EditorFor(model => model.Items[i].ProductName, new { htmlAttributes = new { @class = "form-control" } })</td>

                                        <td class="hidden">@Html.EditorFor(model => model.Items[i].Quantity, new { htmlAttributes = new { @class = "form-control", @Value = "1" } })</td>
                                        <td>@Html.EditorFor(model => model.Items[i].Price, new { htmlAttributes = new { @class = "form-control" } })</td>
                                    </tr>
                                }

                            </tbody>
                        </table>
                        <div class="text-right">
                            <a href="javascript:void(0)" id="addRow" style="font-size:21px;font-weight:bold" class="text-danger" onclick="addRow();"><i class="ti-plus" data-name="mdi-plus"></i> </a>
                        </div>
                    </div>
                </div>


                <div class="form-group text-center">
                    <button type="submit" class="btn btn-primary"><i class="ti ti-check"></i> Đề xuất</button>
                    <a class="btn btn-danger" href="/admin/a_station"><i class="ti ti-close"></i> Thoát</a>
                </div>

            </div>
        }
    </div>
</div>

@section scripts{
    <script>
        function addRow() {
            var index = $("#tblBills").children("tr").length;

            //var code = '<td><select onchange="changeCode(this.id)" class="form-control" id="Items_' + index + '__ProductCode" name="Items[' + index + '].ProductCode"><option>--Select--</option></select></td>'
            var code = '<td><input class="form-control" id="Items_' + index + '__ProductCode" name="Items[' + index + '].ProductCode" type="text" /></td >';
            var name = '<td><input class="form-control" id="Items_' + index + '__ProductName" name="Items[' + index + '].ProductName" type="text" /></td >';
            var model = '<td><input class="form-control" id="Items_' + index + '__ProductModel" name="Items[' + index + '].ProductModel" type="text" onchange="changeModel(this.id)"/></td >';
            var qty = '<td class="hidden"><input class="form-control" id="Items_' + index + '__Quantity" name="Items[' + index + '].Quantity" type="number" value= "1"/></td >';
            var price = '<td><input class="form-control" id="Items_' + index + '__Price" name="Items[' + index + '].Price" type="number" /></td >';

            var newRow = "<tr id='trBook" + index + "'>" + model + code + name + qty + price + "</tr>";
            $("#tblBills").append(newRow);

            $("#Items_" + index + "__ProductCode").autocomplete({
                source: function (request, response) {
                    var model = $("#Items_" + index + "__ProductModel").val();
                    $.ajax({
                        url: "/Admin/A_Station/GetAccessaryByCode",
                        type: "POST",
                        dataType: "json",
                        data: { text: request.term, model: model },
                        success: function (data) {
                            response($.map(data, function (item) {
                                return { value: item.Code, label: item.Code, label1: item.Name, label2: item.Model, label3: item.Price };
                            }))

                        }
                    })
                },
                select: function (event, ui) {
                    $("#Items_" + index + "__ProductName").val(ui.item.label1);
                    $("#Items_" + index + "__ProductModel").val(ui.item.label2);
                    $("#Items_" + index + "__Price").val(ui.item.label3);
                },
                messages: {
                    noResults: "", results: ""
                }
            });

            $("#Items_" + index + "__ProductModel").autocomplete({
                source: function (request, response) {
                    $.ajax({
                        url: "/Admin/A_Station/GetModel",
                        type: "POST",
                        dataType: "json",
                        data: { text: request.term },
                        success: function (data) {
                            response($.map(data, function (item) {
                                return { value: item.Key, label: item.Key };
                            }))

                        }
                    })
                },
                select: function (event, ui) {
                    //$("#Items_" + index + "__ProductName").val(ui.item.label1);
                    //$("#Items_" + index + "__ProductModel").val(ui.item.label2);
                    //$("#Items_" + index + "__Price").val(ui.item.label3);
                },
                messages: {
                    noResults: "", results: ""
                }
            });

        }
        function changeModel(id) {
            //var index = id.split('_')[1];
            //var model = $("#Items_" + index + "__ProductModel").val();
            //$.ajax({
            //    url: "/Admin/A_Station/GetAccessaryByModel",
            //    type: "POST",
            //    dataType: "json",
            //    data: { text: model },
            //    success: function (data) {
            //        $.each(data, function (i, product) {
            //            $("#Items_" + index + "__ProductCode").append($('<option></option>').val(product.Code).html(product.Code))
            //        })
            //    }
            //})
        }
        function changeCode(id) {
            var index = id.split('_')[1];
            var code = $("#Items_" + index + "__ProductCode").val();
            $.ajax({
                url: "/Admin/A_Station/GetPriceByCode",
                type: "POST",
                dataType: "json",
                data: { text: code },
                success: function (data) {
                    $("#Items_" + index + "__ProductName").val(data.Name);
                    $("#Items_" + index + "__Price").val(data.Price);
                }
            })
        }


    </script>
}

Mediamart/Areas/Admin/Views/A_Station/Index.cshtml
@model PagedList.IPagedList<Mediamart.Models.A_Station>
@using PagedList.Mvc;
@{
    ViewBag.Title = "Station";
    int index = 0;
}
<div class="card">
    <div class="card-header">Form filter</div>
    <div class="card-body">
        <div class="row">
            <div class="col-md-12">
                <form class="needs-validation" novalidate>
                    <div class="form-row">
                        <div class="col-md-2 mb-2">
                            <label for="ticket-name" class="col-form-label">Tìm kiếm</label>
                            <div class="">
                                <input type="text" class="form-control" name="textsearch" value="@ViewBag.textsearch">
                            </div>
                        </div>
                        <div class="col-md-2 mb-2">
                            <label for="ticket-type" class="col-sm-9 col-form-label">Kênh</label>
                            <div class="">
                                @Html.DropDownList("status", new List<SelectListItem>{
                                new SelectListItem { Value = "" , Text = "--chọn--" },
                                new SelectListItem { Value = "0" , Text = "Còn hàng" },
                                new SelectListItem { Value = "1" , Text = "Hết hàng" }}, new { @class = "form-control" })
                            </div>
                        </div>
                        <div class="col-md-2 mb-2">
                            <label for="ticket-type" class="col-sm-9 col-form-label">Trạm bảo hành</label>
                            <div class="">
                                @Html.DropDownList("chanel", new SelectList(ViewBag.station, "UserName", "UserName"), "--Chọn--", new { @class = "form-control" })
                            </div>
                        </div>
                        <div class="col-md-3 mb-3">
                            <label for="ticket-type" class="col-sm-9 col-form-label">Ngày tạo</label>
                            <div class="input-daterange input-group" data-provide="datepicker" data-date-format="dd/mm/yyyy">
                                <input class="form-control" name="start_date" value="@ViewBag.start_date">
                                <div class="input-group-prepend">
                                    <span class="input-group-text">to</span>
                                </div>
                                <input class="form-control" name="end_date" value="@ViewBag.end_date">
                            </div>
                        </div>
                    </div>
                    <button class="btn btn-primary" type="submit"><i class="ti ti-filter"></i> Tìm kiếm</button>
                    @if (User.IsInModule("station.add"))
                    {
                        <a class="btn btn-info" href="/admin/a_station/create"><i class="ti ti-plus"></i> Đề xuất</a>
                    }
                </form>
            </div>

        </div>
    </div>
</div>


<div class="card">
    <div class="card-header">
        <h3 class="card-title">Table database</h3>
    </div>
    <div class="card-body">
        <table class="table table-sm" id="table">
            <thead>
                <tr>
                    <th>#</th>
                    <th>Model</th>
                    <th>Tên linh kiện</th>
                    <th>Mã linh kiện</th>
                    <th>Giá</th>
                    <th>Tổng nhập</th>
                    <th>Tổng xuất</th>
                    <th>Còn lại</th>
                    <th>Trạm BH</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    index++;
                    var Point = item.CountImport - item.CountExport;
                    <tr>
                        <td style="display:none">@item.Id</td>
                        <td>@index</td>
                        <td>@item.Model</td>
                        <td>@item.Name</td>
                        <td>@item.Code</td>
                        <td>@item.Price.ToString("N0")</td>
                        <td>
                            @item.CountImport
                        </td>
                        <td>
                            @item.CountExport
                        </td>
                        <td>@Point</td>
                        <td>@item.StationId</td>
                        @*<td>
                            <div class="btn-group">
                                @if (User.IsInRole("Admin - Quản trị toàn hệ thống"))
                                {
                                    <a class="btn btn-outline-light edit" href="#"><i class="ti ti-pencil-alt"></i></a>
                                }
                            </div>
                        </td>*@
                    </tr>
                }
            </tbody>
        </table>
        <div class="row">
            <div class="col-sm-6">
                <div class="showing">Showing @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of @Model.PageCount</div>
            </div>
            <div class="col-sm-6">
                @Html.PagedListPager(Model, page => Url.Action("Index", new { page, textsearch = ViewBag.textsearch, chanel = ViewBag.chanel, status = ViewBag.status, start_date = ViewBag.start_date, end_date = ViewBag.end_date }))
            </div>
        </div>
    </div>
</div>